auth_token: 
server_url: http://localhost:7099
storage_driver: disk
include:
    - .agent
    - .bash_aliases
    - .bashrc
    - .colors
    - .config/glow/glow.yml
    - .dircolors
    - go/bin/
    - .gitconfig
    - .nano
    - .nanorc
    - .oh-my-zsh/plugins/
    - .profile
    - .selected_editor
    - .zshrc
    - .wakeonlan
    - .zprofile
    - .zlogin
    - .zlogout
users:
    root:
        home: /root/
        include: []
    user:
        home: /home/user/
        include: []

redis: 
    addr: ""
    socket: ""
    username: ""
    password: ""
    db: 0
    tls: false
    tls_ca: ""
    tls_insecure_skip_verify: false
    tls_server_name: ""
database:
    driver: "mariadb"
    addr: ""
    socket: ""
    db: ""
    user: ""
    password: ""
    tls: false
    tls_ca: ""
    tls_cert: ""
    tls_key: ""
    tls_insecure_skip_verify: false
    tls_server_name: ""
track:
    - docs/
    - "!docs/config.yaml"