auth_token: pass
server_url: http://cjserver4:7099
storage_driver: disk
track:
    - .agent
    - .bash_aliases
    - .bashrc
    - .colors
    - .config/glow/glow.yml
    - .dircolors
    - .fzf_git
    - .gitconfig
    - .nano/**
    - .nanorc
    - .oh-my-zsh/plugins/**/*.zsh
    - .oh-my-zsh/themes/*.zsh-theme
    - .profile
    - .selected_editor
    - .wakeonlan
    - .zprofile
    - .zlogin
    - .zlogout
    - .zshrc
    - docs/
    - "!docs/config.yaml"
users:
    cjserver:
        home: /home/cjserver/
        track: []
    root:
        home: /root/
        track: []
redis:
    addr: ""
    socket: ""
    username: ""
    password: ""
    db: 0
    tls: false
    tls_ca: ""
    tls_insecure_skip_verify: false
    tls_server_name: ""
db:
    addr: ""
    socket: ""
    db: ""
    user: ""
    password: ""
    tls: false
    tls_ca: ""
    tls_cert: ""
    tls_key: ""
    tls_insecure_skip_verify: false
    tls_server_name: ""
